[icon]
globs = []
dirs  = [
	{ name = ".config", text = "", fg = "#9E9FA2" },
	{ name = ".git", text = "", fg = "#9E9FA2" },
	{ name = ".github", text = "", fg = "#9E9FA2" },
	{ name = ".npm", text = "", fg = "#9E9FA2" },
	{ name = "Desktop", text = "", fg = "#9E9FA2" },
	{ name = "Development", text = "", fg = "#9E9FA2" },
	{ name = "Documents", text = "", fg = "#9E9FA2" },
	{ name = "Downloads", text = "", fg = "#9E9FA2" },
	{ name = "Library", text = "", fg = "#9E9FA2" },
	{ name = "Movies", text = "", fg = "#9E9FA2" },
	{ name = "Music", text = "", fg = "#9E9FA2" },
	{ name = "Pictures", text = "", fg = "#9E9FA2" },
	{ name = "Public", text = "", fg = "#9E9FA2" },
	{ name = "Videos", text = "", fg = "#9E9FA2" },
	{ name = "Python", text = "", fg = "#9E9FA2" },
	{ name = "Java", text = "", fg = "#9E9FA2" },
	{ name = "Lua", text = "", fg = "#9E9FA2" },
	{ name = "C", text = "", fg = "#9E9FA2" },
	{ name = "Cpp", text = "", fg = "#9E9FA2" },
	{ name = "JavaScript", text = "", fg = "#9E9FA2" },
	{ name = "Haskell", text = "", fg = "#9E9FA2" },
	{ name = "Games", text = "󰊗", fg = "#9E9FA2" },
]
conds = [
	{ if = "dir", text = "", fg = "#9E9FA2" }
]
